In [139]:
import pandas as pd

In [140]:
df=pd.read_csv('train.csv')

In [141]:
df1=pd.read_csv('test.csv')

In [142]:
df.head()

,id,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,updated,place,type,horizontalError,depthError,magError,magNst,status,magSource
0,ak023bhr3gi7,2023-09-07T18:04:16.796Z,68.169223,-140.797898,24.70,0.990448,ml,22.574527,113.664517,0.580381,0.200713,2023-09-07T18:05:52.738Z,Central Alaska,earthquake,1.519721,-4.355533,0.22445,15.934177,automatic,0
1,ak023bhqsbjj,2023-09-07T17:52:20.316Z,41.519195,-172.943514,94.60,1.274523,ml,22.574527,113.664517,0.580381,0.229812,2023-09-07T17:54:02.345Z,"35 km WSW of Petersville, Alaska",earthquake,1.519721,28.978306,0.22445,15.934177,automatic,0
2,nc73934281,2023-09-07T17:42:47.850Z,35.197428,-101.446007,-0.46,1.546300,ml,39.000000,118.000000,0.140900,0.093344,2023-09-07T18:06:10.553Z,"13 km S of Redway, CA",earthquake,0.890000,16.598938,0.25900,11.000000,automatic,6
3,ak023bhqliix,2023-09-07T17:20:44.539Z,119.063032,-170.086021,21.90,-1.769233,ml,22.574527,113.664517,0.580381,0.388880,2023-09-07T17:23:12.224Z,"13 km SSE of South Van Horn, Alaska",earthquake,1.519721,2.708122,0.22445,15.934177,automatic,0
4,hv73567917,2023-09-07T17:08:48.580Z,-0.283199,-164.414244,2.08,1.669885,ml,33.000000,166.000000,0.580381,0.228542,2023-09-07T17:14:17.600Z,"15 km NE of Pāhala, Hawaii",earthquake,0.380000,3.135861,2.89000,9.000000,automatic,4

In [143]:
df.drop(['time','updated'],axis=1,inplace=True)
df1.drop(['time','updated'],axis=1,inplace=True)

In [144]:
from sklearn.preprocessing import LabelEncoder

In [145]:
lb=LabelEncoder()

In [146]:
df['typeN']=lb.fit_transform(df['type'])
df['statusN']=lb.fit_transform(df['status'])
df['magtypeN']=lb.fit_transform(df['magType'])
df1['typeN']=lb.fit_transform(df1['type'])
df1['statusN']=lb.fit_transform(df1['status'])
df1['magtypeN']=lb.fit_transform(df1['magType'])

In [147]:
df.drop(['type','status','magType'],axis=1,inplace=True)
df1.drop(['type','status','magType'],axis=1,inplace=True)

In [148]:
df.head()

,id,latitude,longitude,depth,mag,nst,gap,dmin,rms,place,horizontalError,depthError,magError,magNst,magSource,typeN,statusN,magtypeN
0,ak023bhr3gi7,68.169223,-140.797898,24.70,0.990448,22.574527,113.664517,0.580381,0.200713,Central Alaska,1.519721,-4.355533,0.22445,15.934177,0,0,0,4
1,ak023bhqsbjj,41.519195,-172.943514,94.60,1.274523,22.574527,113.664517,0.580381,0.229812,"35 km WSW of Petersville, Alaska",1.519721,28.978306,0.22445,15.934177,0,0,0,4
2,nc73934281,35.197428,-101.446007,-0.46,1.546300,39.000000,118.000000,0.140900,0.093344,"13 km S of Redway, CA",0.890000,16.598938,0.25900,11.000000,6,0,0,4
3,ak023bhqliix,119.063032,-170.086021,21.90,-1.769233,22.574527,113.664517,0.580381,0.388880,"13 km SSE of South Van Horn, Alaska",1.519721,2.708122,0.22445,15.934177,0,0,0,4
4,hv73567917,-0.283199,-164.414244,2.08,1.669885,33.000000,166.000000,0.580381,0.228542,"15 km NE of Pāhala, Hawaii",0.380000,3.135861,2.89000,9.000000,4,0,0,4

In [149]:
df.fillna(df.median(),inplace=True)
df1.fillna(df.median(),inplace=True)

/var/folders/y3/2lx6njq91dz_msk7w16nrqmm0000gn/T/ipykernel_75663/3090946333.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.median(),inplace=True)
/var/folders/y3/2lx6njq91dz_msk7w16nrqmm0000gn/T/ipykernel_75663/3090946333.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df1.fillna(df.median(),inplace=True)

In [150]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [151]:
df.drop(['place','id'],axis=1,inplace=True)

In [152]:
model=DecisionTreeClassifier()

In [153]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(['magSource'],axis=1),df.magSource,test_size=0.3)

In [154]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [155]:
model.score(x_test,y_test)

0.7663373860182371